workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.energye.io
      vars:
        XCODE_WORKSPACE: "ios/energye.xcworkspace"
        XCODE_SCHEME: "energye"
      node: latest
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files --type ios_distribution
      - name: Build iOS app
        script: |
          xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -destination 'generic/platform=iOS' -archivePath build/energye.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/energye.xcarchive
      - /tmp/xcodebuild_logs/*.log